<?php

/**
 * Implement hook_menu()
 * ALL page callbacks are hooked here. 
 */
function csv_menu() {
	$items = array();
	$items['admin/csv'] = array(
		'title' => 'CSV',
		'type' => MENU_NORMAL_ITEM,

		'page callback' => 'csv_main',

        'file' => 'csv.main',

		'access arguments' => array('create content'),
	);

	$items['admin/csv/main'] = array(
		'title' => 'Basic config',
		'type' => MENU_DEFAULT_LOCAL_TASK,

		'page callback' => 'csv_main',

		'access arguments' => array('create content'),
	);

	$items['admin/csv/import'] = array(
		'title' => 'Import',
		'type' => MENU_LOCAL_TASK,

		'page callback' => 'drupal_get_form',
		'page arguments' => array('csv_importer'),

        'file' => 'importer/importer.main',

		'access arguments' => array('create content'),
	);

	$items['admin/csv/import/end'] = array(
		'title' => 'Import finished',

		'page callback' => 'csv_importer_end',

		'file' => 'importer/importer.end',

		'access arguments' => array('create content')
	);

	$items['admin/csv/export'] = array(
		'title' => 'Export CSV',
		'type' => MENU_LOCAL_TASK,
		'weight' => 1,

		'page callback' => 'drupal_get_form',
		'page arguments' => array('csv_exporter'),

		'file' => 'exporter/exporter.main',

		'access arguments' => array('create content')
	);

	$items['admin/csv/exporter/end'] = array(
		'title' => 'Export finished',

		'page callback' => 'csv_exporter_end',

		'file' => 'exporter/exporter.end',

		'access arguments' => array('create content')
	);

	return $items;
}







/**
 * Define a function to get the path to the /csv_module_temp folder
 */
function _csv_get_path_to_temp_dir() {
	$path_to_files = variable_get('file_' . file_default_scheme() . '_path', conf_path() . '/files');

	return $path_to_files . '/csv_module_temp';
}