<?php

/**
 * Implement hook_menu()
 * ALL page callbacks are hooked here. 
 */
function importer_menu() {
	$items = array();
	$items['admin/csv'] = array(
		'title' => 'go CSV',
		'type' => MENU_NORMAL_ITEM,

		'page callback' => 'drupal_get_form',
		'page arguments' => array('importer'),

        'file' => 'importer.form.main.inc',

		'access arguments' => array('create artwork content'),
	);

	$items['admin/importer/end'] = array(
		'title' => 'Importer results',
		'page callback' => 'importer_results_page',

		'access arguments' => array('create artwork content'),
	);

	return $items;
}




function importer_results_page() {
	return 'C\'est fini :D';
}